# Jekyll config â€” exclude heavy folders that should NOT be processed
exclude:
  - node_modules
  - portfolio
  - portfolio/node_modules
  - dist
  - portfolio/dist
  - .github
  - README.md
# Optional: you can add other site-wide settings below
# markdown: kramdown
# theme: jekyll-theme-primer
